/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_
# define VAR_IFONT "y"
# define VAR_IFONTWIDTH "x"
# define VAR_IRESOLUTION "m"
# define VAR_ITIME "v"

const char *gfx_frag =
 "#version 130\n"
 "uniform float v;"
 "uniform vec2 m;"
 "uniform sampler2D y;"
 "uniform float x;"
 "const vec3 s=vec3(1.,0.,-1.);"
 "const float f=acos(-1.);"
 "float i=1.;"
 "vec2 l=vec2(0.,0.);"
 "vec4 t(vec4 v,vec4 s)"
 "{"
   "return vec4(min(v.x,s.x),mix(s.yzw,v.yzw,smoothstep(-1.5/m.y,1.5/m.y,s.x)));"
 "}"
 "float t(vec2 v,vec2 y,vec2 m)"
 "{"
   "vec2 s=m-y;"
   "return length(v-mix(y,m,clamp(dot(v-y,s)/dot(s,s),0.,1.)));"
 "}"
 "float p(float v,float x)"
 "{"
   "return abs(v)-x;"
 "}"
 "float p(vec2 y,vec2 s,vec2 v,vec2 f,float x)"
 "{"
   "return x=clamp(x,0.,1.),length(f-pow(1.-x,2.)*y-2.*(1.-x)*x*s-x*x*v);"
 "}"
 "float p(vec2 v,vec2 x,vec2 y,vec2 m)"
 "{"
   "vec2 i=m-v,z=y-2.*x+v,l=x-v;"
   "vec3 d=vec3(3.*dot(l,z),2.*dot(l,l)-dot(i,z),-dot(i,l))/dot(z,z);"
   "float c=d.x/3.,n=d.y-c*d.x,a=-c*(c*c+n)+d.z,g=a*a/4.+n*n*n/27.;"
   "if(g>0.)"
     "{"
       "vec2 t=-.5*a*s.xx+sqrt(g)*s.xz,r=sign(t)*pow(abs(t),s.xx/3.);"
       "return p(v,x,y,m,r.x+r.y-c);"
     "}"
   "float t=sqrt(-4./3.*n),r=acos(-.5*a*sqrt(-27./n/n/n))/3.;"
   "vec3 e=s.zxz*t*cos(r*s.xxx+s*f/3.)-c;"
   "return min(p(v,x,y,m,e.x),min(p(v,x,y,m,e.y),p(v,x,y,m,e.z)));"
 "}"
 "float p(vec2 y,vec2 v,vec2 m)"
 "{"
   "vec2 s=m-y,d=v-y;"
   "float x,f;"
   "f=s.y/d.y;"
   "x=d.x*f-s.x;"
   "return step(0.,f)*step(f,1.)*step(0.,x);"
 "}"
 "float t(vec2 v,vec2 m,vec2 y,vec2 x)"
 "{"
   "float i=y.y-2.*m.y+v.y,c=2.*m.y-2.*v.y,f=v.y-x.y;"
   "if(v.y==m.y||m.y==y.y)"
     "return t(v,y,x);"
   "float l=c*c-4.*i*f;"
   "if(l==0.)"
     "{"
       "float z=-c/2./i,n=(1.-z)*(1.-z)*v.x+2.*(1.-z)*z*m.x+z*z*y.x-x.x;"
       "return step(0.,z)*step(z,1.)*step(0.,n);"
     "}"
   "else"
     " if(l>0.)"
       "{"
         "vec2 z=(-c*s.xx+s.xz*sqrt(l))/2./i,n=(s.xx-z)*(s.xx-z)*v.x+2.*(s.xx-z)*z*m.x+z*z*y.x-x.x;"
         "z=step(s.yy,z)*step(z,s.xx)*step(s.yy,n);"
         "return z.x+z.y;"
       "}"
   "return 0.;"
 "}"
 "float p(float v)"
 "{"
   "float z=mod(v,2.);"
   "v*=.5;"
   "vec2 s=(vec2(mod(v,x),floor(v/x))+.05)/x;"
   "vec4 m=texture(y,s);"
   "vec2 f=mix(m.xy,m.zw,z);"
   "return dot(vec2(255.,65280.),f);"
 "}"
 "float n(vec2 v,int m)"
 "{"
   "float x=p(0.),f=-1.;"
   "for(float z=0.;z<x;z+=1.)"
     "{"
       "int l=int(p(1.+2.*z));"
       "if(l==m)"
         "{"
           "f=p(1.+2.*z+1);"
           "break;"
         "}"
     "}"
   "if(f==-1.)"
     "return 1.;"
   "vec2 z=mix(s.xx,s.zz,vec2(p(f),p(f+2.)))*vec2(p(f+1.),p(f+3.));"
   "float y=p(f+4.),l=f+5.,n=f+6.+y,c=f+7.+2.*y,r=f+8.+3.*y,e=p(r-1.),d=1.,g=0.;"
   "for(float a=0.;a<e;a+=1.)"
     "{"
       "float k=0.,o=p(r+a);"
       "if(a>0.)"
         "k=p(r+a-1.)+1.;"
       "vec2 u[3];"
       "float b[3];"
       "int w=0;"
       "for(float h=k;h<=o;h+=1.)"
         "{"
           "b[w]=p(c+h);"
           "u[w]=(vec2(p(l+h),p(n+h))+z)/65536.*i;"
           "++w;"
           "if(w==2)"
             "{"
               "if(b[0]*b[1]==1)"
                 "d=min(d,t(v,u[0],u[1])),g+=t(u[0],u[1],v),--h,w=0;"
             "}"
           "else"
             " if(w==3)"
               "{"
                 "if(b[0]*b[2]==1.)"
                   "d=min(d,p(u[0],u[1],u[2],v)),g+=t(u[0],u[1],u[2],v),--h,w=0;"
                 "else"
                   "{"
                     "vec2 q=mix(u[1],u[2],.5);"
                     "d=min(d,p(u[0],u[1],q,v));"
                     "g+=t(u[0],u[1],q,v);"
                     "u[0]=q;"
                     "b[0]=1.;"
                     "--h;"
                     "w=1;"
                   "}"
               "}"
         "}"
       "b[w]=p(c+k);"
       "u[w]=(vec2(p(l+k),p(n+k))+z)/65536.*i;"
       "++w;"
       "if(w==2)"
         "d=min(d,t(v,u[0],u[1])),g+=t(u[0],u[1],v);"
       "else"
         " if(w==3)"
           "d=min(d,p(u[0],u[1],u[2],v)),g+=t(u[0],u[1],u[2],v);"
     "}"
   "for(float w=0.;w<y;w+=1.)"
     "{"
       "vec2 h=(vec2(p(l+w),p(n+w))+z)/65536.*i;"
       "d=min(d,length(v-h)-.002);"
     "}"
   "return mix(d,-d,mod(g,2.));"
 "}"
 "mat2 n(float v)"
 "{"
   "vec2 m=vec2(cos(v),sin(v));"
   "return mat2(m*s.xz,m.yx);"
 "}"
 "void r(out vec4 y,in vec2 x)"
 "{"
   "vec2 s=x/m.yy-.5;"
   "int z=32+int(floor(mod(v,94.)));"
   "vec3 f=.5+.5*cos(s.xyx-v+vec3(0,2,4));"
   "i=.6;"
   "f*=smoothstep(-1.5/m.y,1.5/m.y,n(s,z));"
   "y=vec4(f,1.);"
 "}"
 "void main()"
 "{"
   "r(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
