/* File generated with Shader Minifier 1.1.5
 * http://www.ctrl-alt-test.fr
 */
#ifndef GFX_H_
# define GFX_H_
# define VAR_IFONT "y"
# define VAR_IFONTWIDTH "x"
# define VAR_IRESOLUTION "m"
# define VAR_ITIME "v"

const char *gfx_frag =
 "#version 130\n"
 "uniform float v;"
 "uniform vec2 m;"
 "uniform sampler2D y;"
 "uniform float x;"
 "const vec3 s=vec3(1.,0.,-1.);"
 "const float f=acos(-1.);"
 "float i=1.;"
 "vec2 r=vec2(0.,0.);"
 "vec4 p(vec4 v,vec4 s)"
 "{"
   "return vec4(min(v.x,s.x),mix(s.yzw,v.yzw,smoothstep(-1.5/m.y,1.5/m.y,s.x)));"
 "}"
 "float p(vec2 v,vec2 y,vec2 m)"
 "{"
   "vec2 s=m-y;"
   "return length(v-mix(y,m,clamp(dot(v-y,s)/dot(s,s),0.,1.)));"
 "}"
 "float t(float v,float x)"
 "{"
   "return abs(v)-x;"
 "}"
 "float p(vec2 y,vec2 s,vec2 v,vec2 m,float x)"
 "{"
   "return x=clamp(x,0.,1.),length(m-pow(1.-x,2.)*y-2.*(1.-x)*x*s-x*x*v);"
 "}"
 "float p(vec2 v,vec2 y,vec2 m,vec2 x)"
 "{"
   "vec2 i=x-v,z=m-2.*y+v,w=y-v;"
   "vec3 d=vec3(3.*dot(w,z),2.*dot(w,w)-dot(i,z),-dot(i,w))/dot(z,z);"
   "float r=d.x/3.,c=d.y-r*d.x,t=-r*(r*r+c)+d.z,g=t*t/4.+c*c*c/27.;"
   "if(g>0.)"
     "{"
       "vec2 n=-.5*t*s.xx+sqrt(g)*s.xz,l=sign(n)*pow(abs(n),s.xx/3.);"
       "return p(v,y,m,x,l.x+l.y-r);"
     "}"
   "float n=sqrt(-4./3.*c),l=acos(-.5*t*sqrt(-27./c/c/c))/3.;"
   "vec3 a=s.zxz*n*cos(l*s.xxx+s*f/3.)-r;"
   "return min(p(v,y,m,x,a.x),min(p(v,y,m,x,a.y),p(v,y,m,x,a.z)));"
 "}"
 "float t(vec2 v,vec2 m,vec2 s)"
 "{"
   "if(step(v.y,s.y)*step(s.y,m.y)==0)"
     "return 0;"
   "vec2 d=s-v,f=m-v;"
   "if(f.y==0.)"
     "return 0.;"
   "float y,x;"
   "x=d.y/f.y;"
   "y=f.x*x-d.x;"
   "return step(0.,x)*step(x,1.)*step(0.,y);"
 "}"
 "float t(vec2 v,vec2 y,vec2 m,vec2 x)"
 "{"
   "float i=m.y-2.*y.y+v.y,c=2.*y.y-2.*v.y,f=v.y-x.y,z=c*c-4.*i*f;"
   "if(z==0.)"
     "{"
       "float r=-c/2./i,l=(1.-r)*(1.-r)*v.x+2.*(1.-r)*r*y.x+r*r*m.x-x.x;"
       "return step(0.,r)*step(r,1.)*step(0.,l);"
     "}"
   "else"
     " if(z>0.)"
       "{"
         "vec2 r=(-c*s.xx+s.xz*sqrt(z))/2./i,l=(s.xx-r)*(s.xx-r)*v.x+2.*(s.xx-r)*r*y.x+r*r*m.x-x.x;"
         "r=step(s.yy,r)*step(r,s.xx)*step(s.yy,l);"
         "return r.x+r.y;"
       "}"
   "return 0.;"
 "}"
 "float p(float v)"
 "{"
   "float s=mod(v,2.);"
   "v*=.5;"
   "vec2 r=(vec2(mod(v,x),floor(v/x))+.05)/x;"
   "vec4 m=texture(y,r);"
   "vec2 l=mix(m.xy,m.zw,s);"
   "return round(dot(vec2(255.,65280.),l));"
 "}"
 "float n(vec2 v,int m)"
 "{"
   "float x=p(0.),r=-1.;"
   "for(float y=0.;y<x;y+=1.)"
     "{"
       "int f=int(p(1.+2.*y));"
       "if(f==m)"
         "{"
           "r=p(1.+2.*y+1);"
           "break;"
         "}"
     "}"
   "if(r==-1.)"
     "return 1.;"
   "vec2 y=mix(s.xx,s.zz,vec2(p(r),p(r+2.)))*vec2(p(r+1.),p(r+3.));"
   "float f=p(r+4.),l=r+5.,z=r+6.+f,c=r+7.+2.*f,g=r+8.+3.*f,a=p(g-1.),w=1.,n=0.;"
   "for(float d=0.;d<a;d+=1.)"
     "{"
       "float k=0.,e=p(g+d);"
       "if(d>0.)"
         "k=p(g+d-1.)+1.;"
       "vec2 u[3];"
       "float o[3];"
       "int b=0;"
       "for(float q=k;q<=e;q+=1.)"
         "{"
           "o[b]=p(c+q);"
           "u[b]=(vec2(p(l+q),p(z+q))+y)/65536.*i;"
           "++b;"
           "if(b==2)"
             "{"
               "if(o[0]*o[1]==1)"
                 "w=min(w,p(v,u[0],u[1])),n+=t(u[0],u[1],v),--q,b=0;"
             "}"
           "else"
             " if(b==3)"
               "{"
                 "if(o[0]*o[2]==1.)"
                   "w=min(w,p(u[0],u[1],u[2],v)),n+=t(u[0],u[1],u[2],v),--q,b=0;"
                 "else"
                   "{"
                     "vec2 h=mix(u[1],u[2],.5);"
                     "w=min(w,p(u[0],u[1],h,v));"
                     "n+=t(u[0],u[1],h,v);"
                     "u[0]=h;"
                     "o[0]=1.;"
                     "--q;"
                     "b=1;"
                   "}"
               "}"
         "}"
       "o[b]=p(c+k);"
       "u[b]=(vec2(p(l+k),p(z+k))+y)/65536.*i;"
       "++b;"
       "if(b==2)"
         "w=min(w,p(v,u[0],u[1])),n+=t(u[0],u[1],v);"
       "else"
         " if(b==3)"
           "w=min(w,p(u[0],u[1],u[2],v)),n+=t(u[0],u[1],u[2],v);"
     "}"
   "return mix(w,-w,mod(n,2.));"
 "}"
 "mat2 n(float v)"
 "{"
   "vec2 r=vec2(cos(v),sin(v));"
   "return mat2(r*s.xz,r.yx);"
 "}"
 "void d(out vec4 y,in vec2 x)"
 "{"
   "vec2 s=x/m.yy-.5;"
   "float r=.1;"
   "vec2 w=mod(s,r)-.5*r,u=(s+.5-w)/r;"
   "int l=32+int(mod(floor(u.y/r+u.x),94.));"
   "vec3 f=.5+.5*cos(v+s.xyx+vec3(0,2,4));"
   "i=.54;"
   "f*=smoothstep(-1.5/m.y,1.5/m.y,t(n(w,l),.001));"
   "y=vec4(f,1.);"
 "}"
 "void main()"
 "{"
   "d(gl_FragColor,gl_FragCoord.xy);"
 "}";

#endif // GFX_H_
